server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  #    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: test
#    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


